export const cartActionsTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT_AND_DELETE: "DECREMENT_AND_DELETE",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_ITEM: "DELETE_ITEM",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
};
